version: '3'
services:
  db:
    image: mysql:latest 
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=puapp
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:ro
  api-service:
    image: docker.io/benschreiber/gpra:latest
    restart: always
    ports:
      - "80:8080"
    expose:
      - 8080
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_ADDRESS=db:3306
      - DB_PROTOCOL=tcp
      - DB_NAME=puapp
    depends_on:
      - db
    links:
      - db

volumes:
  db_volume:

